### ISSUE TITLE
Hi I am blog distributor

### ISSUE THREAD

**Issue by junha1125** [House-Leo/House-Leo.github.io#1]
Hi 
I am junha song which is the host of this blog(https://junha1125.github.io/)
I am glad you to enjoy to use my blog package. 

But I have a problem. 
Information about your blog visitor is delivered to me like below.
![image](https://user-images.githubusercontent.com/46951365/117095762-30cd4c00-ada2-11eb-8111-a58564459ad8.png)

Can you delete "Google analytics data" in your code of House-Leo.github.io.

this is how to delete "Google analytics infomation" 
Please just delete below all contents.
**_includes\body\analytics.html** 
```html
....
    w.ga(function(tracker) {
        w.ga("set", "an....eIp", undefined);
        localStorage && localStorage.setItem("g.....id", tracker.get("clientId"));
      });
    });
   
    w.loadJSDeferred('<https://www.google-analytics.com/analytics.js>');
  }(window, document);</script>
     
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="<https://www.googletagmanager.com/gtag/js?id=G-6>....VJQ"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
   
    gtag('config', 'G-68...JQ');
  </script>
```

**Comment by House-Leo** [comment]
Hi, Junha.
Thanks for your blog package.
I am so sorry that this happened because of my fault.
I am on vacation now, so I will solve the problem in two or three days. 
I won't update my blog until I solve the problem.
I'm sorry again for the trouble this incident has caused to you.

**Comment by junha1125** [comment]
Dear. House-leo

Thank you for your quick reply.

It is totally OKEY that you can not solve the problem at the moment.
Plase reply again and close this issue after fixing your code. 

Have a nice vacation. 
Thank you.

junha song

**Comment by House-Leo** [comment]
> Dear. House-leo
> 
> Thank you for your quick reply.
> 
> It is totally OKEY that you can not solve the problem at the moment.
> Plase reply again and close this issue after fixing your code.
> 
> Have a nice vacation.
> Thank you.
> 
> junha song

Hi, Junha.

I have fixed the code just now. 

For testing, I have updated a new post, please check your Google analytics to see if you can get new information.

Please feel free to contact me if something similar happens. Thanks again for your blog sharing, it helps me a lot.

Have a good day.

House-Leo
(I have closed the issue. Open it again if you have a new problem.)

**Comment by House-Leo** [comment]
> Dear. House-leo
> 
> Thank you for your quick reply.
> 
> It is totally OKEY that you can not solve the problem at the moment.
> Plase reply again and close this issue after fixing your code.
> 
> Have a nice vacation.
> Thank you.
> 
> junha song

Hi, Junha.

I have fixed the code just now. 

For testing, I have updated a new post, please check your Google analytics to see if you can get new information.

Please feel free to contact me if something similar happens. Thanks again for your blog sharing, it helps me a lot.

Have a good day.

House-Leo
(I have closed the issue. Open it again if you have a new problem.)

**Comment by junha1125** [comment]
Thank you for solving the problem.

Have a good day ☺️😊
